### ISSUE TITLE
Unvalidated account access to wallet

### ISSUE THREAD

**Issue by tilleyd** [larcai/cornuex#5]
With an unverified account, visiting the [wallet URL](http://demo.cornuex.com/wallet) directly will still allow access to the wallet. I still successfully made a deposit into the bitcoin wallet, even though there are still uncleared validation checks.

###### Reproducing the bug
* On an unverified account, go to http://demo.cornuex.com/wallet
* Instead of redirecting to the home page or giving an error, the wallets are all fully accessible

**Comment by svsnux** [comment]
made fix, please test

**Comment by tilleyd** [comment]
When trying this now, I can't access the wallet but an error message comes up saying

` Fatal Error!
An unresolved error has occured. Do you want to reload the page to correct this? `

After clicking Cancel or OK, the message disappears, reloads the wallet page and the error message reappears, instead of redirecting somewhere else. It's probably not too serious since the wallet can't be accessed, but redirecting the user will look much smoother.

**Comment by svsnux** [comment]
fixed, please test and close
