### ISSUE TITLE
Broken trade button and shortcuts

### ISSUE THREAD

**Issue by tilleyd** [larcai/cornuex#6]
On the exchange page, the **Click to Trade...** button shown on the graph does not work. Possibly related, after the **Click to Trade...** button is clicked, the trading dialog no longer appears when you click on an **order** or a **trade**.

###### Reproduce the issue

* Go to the exchange page
* Click on an **order** or a **trade**, the trading dialog should appear
* Now click on the **Click to Trade...** button, nothing happens
* Click on an order or a trade again, this time nothing happens

---
Edit: The normal **Trade** button always works, even after clicking on the **Click to Trade...** button.

**Comment by svsnux** [comment]
removed the button
